version: '3.8'

services:
  rules:
    build: ./rules
    container_name: soc-rules
    volumes:
      - ./data:/data:ro
      - ./shared:/shared
    environment:
      - DATA_DIR=/data
      - OUTPUT_DIR=/shared
    networks:
      - soc-network

  agent:
    build: ./agent
    container_name: soc-agent
    volumes:
      - ./shared:/shared
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - ALERTS_FILE=/shared/alerts.json
      - TRIAGE_FILE=/shared/triage.json
      - FEEDBACK_FILE=/shared/feedback.json
    depends_on:
      - rules
    networks:
      - soc-network

  web:
    build: ./web
    container_name: soc-web
    ports:
      - "8080:8080"
    volumes:
      - ./shared:/shared:ro
    environment:
      - TRIAGE_FILE=/shared/triage.json
      - FEEDBACK_FILE=/shared/feedback.json
      - ALERTS_FILE=/shared/alerts.json
      - PORT=8080
    depends_on:
      - agent
    networks:
      - soc-network

networks:
  soc-network:
    driver: bridge
