version: '3.8'

services:
  rules:
    build: ./rules
    volumes:
      - ./data:/data:ro
      - ./shared:/shared
    environment:
      - DATA_DIR=/data
      - OUTPUT_DIR=/shared

  agent:
    build: ./agent
    depends_on:
      - rules
    volumes:
      - ./shared:/shared
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - ALERTS_FILE=/shared/alerts.json
      - TRIAGE_FILE=/shared/triage.json
      - FEEDBACK_FILE=/shared/feedback.json

  web:
    build: ./web
    depends_on:
      - agent
    ports:
      - "8080:8080"
    volumes:
      - ./shared:/shared:ro
    environment:
      - TRIAGE_FILE=/shared/triage.json
      - FEEDBACK_FILE=/shared/feedback.json
